name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    permissions:
      contents: read
      checks: write  # for test results
    strategy:
      matrix:
        node: ["20.x", "22.x"]
        platform: [ubuntu-latest]
    name: Node v${{matrix.node}} ((${{matrix.platform}}))
    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: ${{matrix.node}}
      - name: install dependencies
        run: npm ci
      - name: lint code
        run: npm run lint
      - name: build project
        run: npm run build
      - name: run tests
        run: npm run test
      - name: coverage
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
        if: github.actor != 'dependabot[bot]'
        with:
          fail_ci_if_error: true
          verbose: false
          token: ${{ secrets.CODECOV_TOKEN }}
        env:
          CI: true

  release-preview:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: "22.x"
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run build
      - name: release preview with pkr-pr-new
        run: npx pkg-pr-new publish