name: Markdown Lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  markdown_lint:
    name: Lint Markdown files
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Markdown Lint
        uses: ruzickap/action-my-markdown-linter@26b4129bf0352527e60b5bd739357af63df1b7bf # v1.0.0
        with:
          debug: true
          config_file: .github/.markdownlint.yml
          exclude: |
            .changeset/
            .github/
            CODE_OF_CONDUCT.md
            LICENSE
            CHANGELOG.md